language: c
sudo: required
dist: focal
os: linux
arch: arm64-graviton2

script:
 - sudo dpkg --add-architecture i386 
 - wget -nc https://dl.winehq.org/wine-builds/winehq.key
 - sudo apt-key add winehq.key && sudo apt update
 - sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
 - sudo apt update && sudo apt install libc6 libc6:i386 xvfb cabextract -y -o APT::Immediate-Configure=0 && sudo apt install --install-recommends winehq-stable
 - export DISPLAY=':99.0'
 - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
 - wget -q --content-disposition https://go.microsoft.com/fwlink/?LinkID=75078
 - wget -q https://gist.github.com/mmtrt/73db349fec787bcc5dd33ff0d6726553/raw/5c23a358d5d809087725728a4783bfb087b327fd/ztr.txt
 - bash -ex deploy.sh

env:
  global:
    - RELEASE_BRANCH="master"
 
after_success:
  - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh

  - |- # publish
    if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh ./foobar2000*.AppImage*
    elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh ./foobar2000*.AppImage*
    else
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh ./foobar2000*.AppImage*
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/
