language: c
sudo: required
dist: bionic
os: linux

script:
 - bash -ex deploy.sh
 
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ./foobar2000*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
