#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

progName="foobar2000"
progArch="-x86_64"
progVer=
progRealPath="$HERE/usr/share/$progName"
progHome="$HOME/.$progName"
progBin="$progName.exe"
progIcoD="$HOME/.local/share/applications/$progName.desktop"
progUiFix="$progHome/configuration/foo_ui_std.dll.cfg"

# Symlink stuff
mkdir -p "$progHome" || exit 1
# Delete broken symlinks
find -L "$progHome" -maxdepth 2 -type l -delete
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" 2> /dev/null
# fix ui glitch
rm "$progUiFix" 2> /dev/null


gendskfile () {
mkdir -p "${HOME}/.local/share/applications"
DesktopFilePath="${HOME}/.local/share/applications/$progName.desktop"

echo "[Desktop Entry]" >$DesktopFilePath
echo "Type=Application" >>$DesktopFilePath
echo "Name=$progName" >>$DesktopFilePath
echo "GenericName=Audio player" >>$DesktopFilePath
echo "Comment=Simple and powerful audio player." >>$DesktopFilePath
echo "Actions=PlayPause;Stop;Next;Prev;Random;Config" >>$DesktopFilePath
echo "Encoding=UTF-8" >>$DesktopFilePath
echo "Version=$progVer" >>$DesktopFilePath
echo "Icon=$progName" >>$DesktopFilePath
echo "TryExec=${OWD}/${progName}_${progVer}${progArch}.AppImage" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage %F" >>$DesktopFilePath
echo "MimeType=audio/aac;audio/x-ape;audio/basic;audio/mp4;audio/mpeg;audio/mpegurl;audio/vorbis;audio/x-flac;audio/x-mp2;audio/x-mp3;audio/x-mpegurl;audio/x-ms-wma;audio/x-oggflac;audio/x-speex;audio/x-vorbis;audio/x-wav;audio/m3u;audio/x-aifc;audio/x-aiffc;audio/x-aiff;audio/x-musepack;audio/x-wavpack;x-content/audio-player;audio/x-matroska;audio/x-vorbis+ogg;" >>$DesktopFilePath
echo "Categories=AudioVideo;Audio;Player;" >>$DesktopFilePath
echo "Terminal=false" >>$DesktopFilePath
echo "StartupWMClass=$progBin" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action PlayPause]" >>$DesktopFilePath
echo "Name=Play/Pause" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -playpause" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action Stop]" >>$DesktopFilePath
echo "Name=Stop" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -stop" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action Next]" >>$DesktopFilePath
echo "Name=Next" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -next" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action Prev]" >>$DesktopFilePath
echo "Name=Prev" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -prev" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action Random]" >>$DesktopFilePath
echo "Name=Random" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -rand" >>$DesktopFilePath
echo "" >>$DesktopFilePath
echo "[Desktop Action Config]" >>$DesktopFilePath
echo "Name=Preferences" >>$DesktopFilePath
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage -config" >>$DesktopFilePath
}

if [[ ! -f $progIcoD ]]; then

cp -r $HERE/usr/share/icons ${HOME}/.local/share
gendskfile

fi

# check for wine appimage
checkwine=$(find $HOME/Downloads $HOME/bin $HOME/.local/bin -type f \( -name '*.appimage' -o -name '*.AppImage' \) 2>/dev/null | grep -e "wine-stable" -e 'Wine-stable' | head -n 1 | wc -l)

if [ $checkwine -eq 1 ]; then
export WINESERVER=$HERE/usr/bin/wineserver
export WINE=$HERE/usr/bin/wine
export WINETRICKS=$HERE/usr/bin/winetricks
else
notify-send --icon "foobar2000" "Downloading WINE-STABLE appimage from https://github.com/mmtrt/Wine_Appimage/releases Please Wait..."
wget "https://github.com/mmtrt/Wine_Appimage/releases/download/continuous/wine-stable-i386_x86_64-bionic.AppImage" -P $HOME/Downloads
chmod +x $HOME/Downloads/wine-stable-i386_x86_64-bionic.AppImage
notify-send --icon "foobar2000" "Now run Appimage again"
exit 1
fi

# Create custom $WINEPREFIX and add $WINEDLLOVERRIDES
export WINEPREFIX="${progHome}/.wine" WINEDLLOVERRIDES="mscoree,mshtml=;winemenubuilder.exe=d" WINEDEBUG=-all

if [ ! -d $WINEPREFIX ]; then

# link ttf & ttc fonts from root to wineprefix
mkdir -p $WINEPREFIX/drive_c/windows/Fonts
find /usr/share/fonts/ -type f \( -name "*.ttf" -o -name "*.ttc" \) -exec ln -vs "{}" $WINEPREFIX/drive_c/windows/Fonts/ \; &>/dev/null

wget "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -P /tmp && chmod +x /tmp/winetricks
wget "http://archive.ubuntu.com/ubuntu/pool/universe/c/cabextract/cabextract_1.6-1.1_i386.deb" -P /tmp
wget "http://archive.ubuntu.com/ubuntu/pool/main/libm/libmspack/libmspack0_0.6-3ubuntu0.2_i386.deb" -P /tmp

# unpacking cabextract to tmp/cabex
dpkg -x /tmp/cabextract_1.6-1.1_i386.deb /tmp/cabex && dpkg -x /tmp/libmspack0_0.6-3ubuntu0.2_i386.deb /tmp/cabex

# adding cabextract winetricks env
export PATH=$PATH:/tmp:/tmp/cabex/usr/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/cabex/usr/lib/i386-linux-gnu
export PATH=$PATH:/tmp:/tmp/cabex/usr/bin

# running winetricks from tmp
/tmp/winetricks --unattended wmp9 vcrun2017
# removing cache data
rm -r /tmp/winetricks && rm -rf /tmp/cabex && rm /tmp/*.deb

echo "disable" > "$WINEPREFIX/.update-timestamp"
fi

# Passing args to wine apps
for i; do # for i = for i in "$@"
    # Add path in Wine form (e.g. "z:/home/user/Desktop/lol.xyz")
    if [[ -f /${i#?:} ]]; then 
        args+=("z:${i#?:}")   # When opened through .desktop or Wine path (e.g. z:/*)
    elif [[ "${i:0:1}" = "-" ]]; then
        args+=("${i/#-//}")
    fi
done

if [ "$1" == "winecfg" ] ; then
  $WINE "winecfg" 2>/dev/null
else
  $WINE "$progHome/$progBin" "${args[@]}" 2>/dev/null
fi
