# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -ex
          sudo apt install -y p7zip-full
          ./deploy
          mv foobar2000*.AppImage* dist/.
          cd dist
          chmod +x *.AppImage
          cd ..


      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: foobar2000-continuous-x86_64.AppImage
          path: 'foobar2000/dist'
